/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package javaInterface;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-05-21")
public class SubobjectiveDetails implements org.apache.thrift.TBase<SubobjectiveDetails, SubobjectiveDetails._Fields>, java.io.Serializable, Cloneable, Comparable<SubobjectiveDetails> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SubobjectiveDetails");

  private static final org.apache.thrift.protocol.TField PARAM_FIELD_DESC = new org.apache.thrift.protocol.TField("param", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField ATTR_NAMES_FIELD_DESC = new org.apache.thrift.protocol.TField("attr_names", org.apache.thrift.protocol.TType.LIST, (short)2);
  private static final org.apache.thrift.protocol.TField ATTR_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("attr_values", org.apache.thrift.protocol.TType.LIST, (short)3);
  private static final org.apache.thrift.protocol.TField SCORES_FIELD_DESC = new org.apache.thrift.protocol.TField("scores", org.apache.thrift.protocol.TType.LIST, (short)4);
  private static final org.apache.thrift.protocol.TField TAKEN_BY_FIELD_DESC = new org.apache.thrift.protocol.TField("taken_by", org.apache.thrift.protocol.TType.LIST, (short)5);
  private static final org.apache.thrift.protocol.TField JUSTIFICATIONS_FIELD_DESC = new org.apache.thrift.protocol.TField("justifications", org.apache.thrift.protocol.TType.LIST, (short)6);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new SubobjectiveDetailsStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new SubobjectiveDetailsTupleSchemeFactory();

  public java.lang.String param; // required
  public java.util.List<java.lang.String> attr_names; // required
  public java.util.List<java.util.List<java.lang.String>> attr_values; // required
  public java.util.List<java.lang.Double> scores; // required
  public java.util.List<java.lang.String> taken_by; // required
  public java.util.List<java.util.List<java.lang.String>> justifications; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PARAM((short)1, "param"),
    ATTR_NAMES((short)2, "attr_names"),
    ATTR_VALUES((short)3, "attr_values"),
    SCORES((short)4, "scores"),
    TAKEN_BY((short)5, "taken_by"),
    JUSTIFICATIONS((short)6, "justifications");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PARAM
          return PARAM;
        case 2: // ATTR_NAMES
          return ATTR_NAMES;
        case 3: // ATTR_VALUES
          return ATTR_VALUES;
        case 4: // SCORES
          return SCORES;
        case 5: // TAKEN_BY
          return TAKEN_BY;
        case 6: // JUSTIFICATIONS
          return JUSTIFICATIONS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PARAM, new org.apache.thrift.meta_data.FieldMetaData("param", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ATTR_NAMES, new org.apache.thrift.meta_data.FieldMetaData("attr_names", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.ATTR_VALUES, new org.apache.thrift.meta_data.FieldMetaData("attr_values", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)))));
    tmpMap.put(_Fields.SCORES, new org.apache.thrift.meta_data.FieldMetaData("scores", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE))));
    tmpMap.put(_Fields.TAKEN_BY, new org.apache.thrift.meta_data.FieldMetaData("taken_by", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.JUSTIFICATIONS, new org.apache.thrift.meta_data.FieldMetaData("justifications", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SubobjectiveDetails.class, metaDataMap);
  }

  public SubobjectiveDetails() {
  }

  public SubobjectiveDetails(
    java.lang.String param,
    java.util.List<java.lang.String> attr_names,
    java.util.List<java.util.List<java.lang.String>> attr_values,
    java.util.List<java.lang.Double> scores,
    java.util.List<java.lang.String> taken_by,
    java.util.List<java.util.List<java.lang.String>> justifications)
  {
    this();
    this.param = param;
    this.attr_names = attr_names;
    this.attr_values = attr_values;
    this.scores = scores;
    this.taken_by = taken_by;
    this.justifications = justifications;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SubobjectiveDetails(SubobjectiveDetails other) {
    if (other.isSetParam()) {
      this.param = other.param;
    }
    if (other.isSetAttr_names()) {
      java.util.List<java.lang.String> __this__attr_names = new java.util.ArrayList<java.lang.String>(other.attr_names);
      this.attr_names = __this__attr_names;
    }
    if (other.isSetAttr_values()) {
      java.util.List<java.util.List<java.lang.String>> __this__attr_values = new java.util.ArrayList<java.util.List<java.lang.String>>(other.attr_values.size());
      for (java.util.List<java.lang.String> other_element : other.attr_values) {
        java.util.List<java.lang.String> __this__attr_values_copy = new java.util.ArrayList<java.lang.String>(other_element);
        __this__attr_values.add(__this__attr_values_copy);
      }
      this.attr_values = __this__attr_values;
    }
    if (other.isSetScores()) {
      java.util.List<java.lang.Double> __this__scores = new java.util.ArrayList<java.lang.Double>(other.scores);
      this.scores = __this__scores;
    }
    if (other.isSetTaken_by()) {
      java.util.List<java.lang.String> __this__taken_by = new java.util.ArrayList<java.lang.String>(other.taken_by);
      this.taken_by = __this__taken_by;
    }
    if (other.isSetJustifications()) {
      java.util.List<java.util.List<java.lang.String>> __this__justifications = new java.util.ArrayList<java.util.List<java.lang.String>>(other.justifications.size());
      for (java.util.List<java.lang.String> other_element : other.justifications) {
        java.util.List<java.lang.String> __this__justifications_copy = new java.util.ArrayList<java.lang.String>(other_element);
        __this__justifications.add(__this__justifications_copy);
      }
      this.justifications = __this__justifications;
    }
  }

  public SubobjectiveDetails deepCopy() {
    return new SubobjectiveDetails(this);
  }

  @Override
  public void clear() {
    this.param = null;
    this.attr_names = null;
    this.attr_values = null;
    this.scores = null;
    this.taken_by = null;
    this.justifications = null;
  }

  public java.lang.String getParam() {
    return this.param;
  }

  public SubobjectiveDetails setParam(java.lang.String param) {
    this.param = param;
    return this;
  }

  public void unsetParam() {
    this.param = null;
  }

  /** Returns true if field param is set (has been assigned a value) and false otherwise */
  public boolean isSetParam() {
    return this.param != null;
  }

  public void setParamIsSet(boolean value) {
    if (!value) {
      this.param = null;
    }
  }

  public int getAttr_namesSize() {
    return (this.attr_names == null) ? 0 : this.attr_names.size();
  }

  public java.util.Iterator<java.lang.String> getAttr_namesIterator() {
    return (this.attr_names == null) ? null : this.attr_names.iterator();
  }

  public void addToAttr_names(java.lang.String elem) {
    if (this.attr_names == null) {
      this.attr_names = new java.util.ArrayList<java.lang.String>();
    }
    this.attr_names.add(elem);
  }

  public java.util.List<java.lang.String> getAttr_names() {
    return this.attr_names;
  }

  public SubobjectiveDetails setAttr_names(java.util.List<java.lang.String> attr_names) {
    this.attr_names = attr_names;
    return this;
  }

  public void unsetAttr_names() {
    this.attr_names = null;
  }

  /** Returns true if field attr_names is set (has been assigned a value) and false otherwise */
  public boolean isSetAttr_names() {
    return this.attr_names != null;
  }

  public void setAttr_namesIsSet(boolean value) {
    if (!value) {
      this.attr_names = null;
    }
  }

  public int getAttr_valuesSize() {
    return (this.attr_values == null) ? 0 : this.attr_values.size();
  }

  public java.util.Iterator<java.util.List<java.lang.String>> getAttr_valuesIterator() {
    return (this.attr_values == null) ? null : this.attr_values.iterator();
  }

  public void addToAttr_values(java.util.List<java.lang.String> elem) {
    if (this.attr_values == null) {
      this.attr_values = new java.util.ArrayList<java.util.List<java.lang.String>>();
    }
    this.attr_values.add(elem);
  }

  public java.util.List<java.util.List<java.lang.String>> getAttr_values() {
    return this.attr_values;
  }

  public SubobjectiveDetails setAttr_values(java.util.List<java.util.List<java.lang.String>> attr_values) {
    this.attr_values = attr_values;
    return this;
  }

  public void unsetAttr_values() {
    this.attr_values = null;
  }

  /** Returns true if field attr_values is set (has been assigned a value) and false otherwise */
  public boolean isSetAttr_values() {
    return this.attr_values != null;
  }

  public void setAttr_valuesIsSet(boolean value) {
    if (!value) {
      this.attr_values = null;
    }
  }

  public int getScoresSize() {
    return (this.scores == null) ? 0 : this.scores.size();
  }

  public java.util.Iterator<java.lang.Double> getScoresIterator() {
    return (this.scores == null) ? null : this.scores.iterator();
  }

  public void addToScores(double elem) {
    if (this.scores == null) {
      this.scores = new java.util.ArrayList<java.lang.Double>();
    }
    this.scores.add(elem);
  }

  public java.util.List<java.lang.Double> getScores() {
    return this.scores;
  }

  public SubobjectiveDetails setScores(java.util.List<java.lang.Double> scores) {
    this.scores = scores;
    return this;
  }

  public void unsetScores() {
    this.scores = null;
  }

  /** Returns true if field scores is set (has been assigned a value) and false otherwise */
  public boolean isSetScores() {
    return this.scores != null;
  }

  public void setScoresIsSet(boolean value) {
    if (!value) {
      this.scores = null;
    }
  }

  public int getTaken_bySize() {
    return (this.taken_by == null) ? 0 : this.taken_by.size();
  }

  public java.util.Iterator<java.lang.String> getTaken_byIterator() {
    return (this.taken_by == null) ? null : this.taken_by.iterator();
  }

  public void addToTaken_by(java.lang.String elem) {
    if (this.taken_by == null) {
      this.taken_by = new java.util.ArrayList<java.lang.String>();
    }
    this.taken_by.add(elem);
  }

  public java.util.List<java.lang.String> getTaken_by() {
    return this.taken_by;
  }

  public SubobjectiveDetails setTaken_by(java.util.List<java.lang.String> taken_by) {
    this.taken_by = taken_by;
    return this;
  }

  public void unsetTaken_by() {
    this.taken_by = null;
  }

  /** Returns true if field taken_by is set (has been assigned a value) and false otherwise */
  public boolean isSetTaken_by() {
    return this.taken_by != null;
  }

  public void setTaken_byIsSet(boolean value) {
    if (!value) {
      this.taken_by = null;
    }
  }

  public int getJustificationsSize() {
    return (this.justifications == null) ? 0 : this.justifications.size();
  }

  public java.util.Iterator<java.util.List<java.lang.String>> getJustificationsIterator() {
    return (this.justifications == null) ? null : this.justifications.iterator();
  }

  public void addToJustifications(java.util.List<java.lang.String> elem) {
    if (this.justifications == null) {
      this.justifications = new java.util.ArrayList<java.util.List<java.lang.String>>();
    }
    this.justifications.add(elem);
  }

  public java.util.List<java.util.List<java.lang.String>> getJustifications() {
    return this.justifications;
  }

  public SubobjectiveDetails setJustifications(java.util.List<java.util.List<java.lang.String>> justifications) {
    this.justifications = justifications;
    return this;
  }

  public void unsetJustifications() {
    this.justifications = null;
  }

  /** Returns true if field justifications is set (has been assigned a value) and false otherwise */
  public boolean isSetJustifications() {
    return this.justifications != null;
  }

  public void setJustificationsIsSet(boolean value) {
    if (!value) {
      this.justifications = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case PARAM:
      if (value == null) {
        unsetParam();
      } else {
        setParam((java.lang.String)value);
      }
      break;

    case ATTR_NAMES:
      if (value == null) {
        unsetAttr_names();
      } else {
        setAttr_names((java.util.List<java.lang.String>)value);
      }
      break;

    case ATTR_VALUES:
      if (value == null) {
        unsetAttr_values();
      } else {
        setAttr_values((java.util.List<java.util.List<java.lang.String>>)value);
      }
      break;

    case SCORES:
      if (value == null) {
        unsetScores();
      } else {
        setScores((java.util.List<java.lang.Double>)value);
      }
      break;

    case TAKEN_BY:
      if (value == null) {
        unsetTaken_by();
      } else {
        setTaken_by((java.util.List<java.lang.String>)value);
      }
      break;

    case JUSTIFICATIONS:
      if (value == null) {
        unsetJustifications();
      } else {
        setJustifications((java.util.List<java.util.List<java.lang.String>>)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case PARAM:
      return getParam();

    case ATTR_NAMES:
      return getAttr_names();

    case ATTR_VALUES:
      return getAttr_values();

    case SCORES:
      return getScores();

    case TAKEN_BY:
      return getTaken_by();

    case JUSTIFICATIONS:
      return getJustifications();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case PARAM:
      return isSetParam();
    case ATTR_NAMES:
      return isSetAttr_names();
    case ATTR_VALUES:
      return isSetAttr_values();
    case SCORES:
      return isSetScores();
    case TAKEN_BY:
      return isSetTaken_by();
    case JUSTIFICATIONS:
      return isSetJustifications();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof SubobjectiveDetails)
      return this.equals((SubobjectiveDetails)that);
    return false;
  }

  public boolean equals(SubobjectiveDetails that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_param = true && this.isSetParam();
    boolean that_present_param = true && that.isSetParam();
    if (this_present_param || that_present_param) {
      if (!(this_present_param && that_present_param))
        return false;
      if (!this.param.equals(that.param))
        return false;
    }

    boolean this_present_attr_names = true && this.isSetAttr_names();
    boolean that_present_attr_names = true && that.isSetAttr_names();
    if (this_present_attr_names || that_present_attr_names) {
      if (!(this_present_attr_names && that_present_attr_names))
        return false;
      if (!this.attr_names.equals(that.attr_names))
        return false;
    }

    boolean this_present_attr_values = true && this.isSetAttr_values();
    boolean that_present_attr_values = true && that.isSetAttr_values();
    if (this_present_attr_values || that_present_attr_values) {
      if (!(this_present_attr_values && that_present_attr_values))
        return false;
      if (!this.attr_values.equals(that.attr_values))
        return false;
    }

    boolean this_present_scores = true && this.isSetScores();
    boolean that_present_scores = true && that.isSetScores();
    if (this_present_scores || that_present_scores) {
      if (!(this_present_scores && that_present_scores))
        return false;
      if (!this.scores.equals(that.scores))
        return false;
    }

    boolean this_present_taken_by = true && this.isSetTaken_by();
    boolean that_present_taken_by = true && that.isSetTaken_by();
    if (this_present_taken_by || that_present_taken_by) {
      if (!(this_present_taken_by && that_present_taken_by))
        return false;
      if (!this.taken_by.equals(that.taken_by))
        return false;
    }

    boolean this_present_justifications = true && this.isSetJustifications();
    boolean that_present_justifications = true && that.isSetJustifications();
    if (this_present_justifications || that_present_justifications) {
      if (!(this_present_justifications && that_present_justifications))
        return false;
      if (!this.justifications.equals(that.justifications))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetParam()) ? 131071 : 524287);
    if (isSetParam())
      hashCode = hashCode * 8191 + param.hashCode();

    hashCode = hashCode * 8191 + ((isSetAttr_names()) ? 131071 : 524287);
    if (isSetAttr_names())
      hashCode = hashCode * 8191 + attr_names.hashCode();

    hashCode = hashCode * 8191 + ((isSetAttr_values()) ? 131071 : 524287);
    if (isSetAttr_values())
      hashCode = hashCode * 8191 + attr_values.hashCode();

    hashCode = hashCode * 8191 + ((isSetScores()) ? 131071 : 524287);
    if (isSetScores())
      hashCode = hashCode * 8191 + scores.hashCode();

    hashCode = hashCode * 8191 + ((isSetTaken_by()) ? 131071 : 524287);
    if (isSetTaken_by())
      hashCode = hashCode * 8191 + taken_by.hashCode();

    hashCode = hashCode * 8191 + ((isSetJustifications()) ? 131071 : 524287);
    if (isSetJustifications())
      hashCode = hashCode * 8191 + justifications.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(SubobjectiveDetails other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetParam()).compareTo(other.isSetParam());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetParam()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.param, other.param);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetAttr_names()).compareTo(other.isSetAttr_names());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAttr_names()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.attr_names, other.attr_names);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetAttr_values()).compareTo(other.isSetAttr_values());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAttr_values()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.attr_values, other.attr_values);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetScores()).compareTo(other.isSetScores());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetScores()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.scores, other.scores);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetTaken_by()).compareTo(other.isSetTaken_by());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTaken_by()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.taken_by, other.taken_by);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetJustifications()).compareTo(other.isSetJustifications());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetJustifications()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.justifications, other.justifications);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("SubobjectiveDetails(");
    boolean first = true;

    sb.append("param:");
    if (this.param == null) {
      sb.append("null");
    } else {
      sb.append(this.param);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("attr_names:");
    if (this.attr_names == null) {
      sb.append("null");
    } else {
      sb.append(this.attr_names);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("attr_values:");
    if (this.attr_values == null) {
      sb.append("null");
    } else {
      sb.append(this.attr_values);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("scores:");
    if (this.scores == null) {
      sb.append("null");
    } else {
      sb.append(this.scores);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("taken_by:");
    if (this.taken_by == null) {
      sb.append("null");
    } else {
      sb.append(this.taken_by);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("justifications:");
    if (this.justifications == null) {
      sb.append("null");
    } else {
      sb.append(this.justifications);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SubobjectiveDetailsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SubobjectiveDetailsStandardScheme getScheme() {
      return new SubobjectiveDetailsStandardScheme();
    }
  }

  private static class SubobjectiveDetailsStandardScheme extends org.apache.thrift.scheme.StandardScheme<SubobjectiveDetails> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SubobjectiveDetails struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PARAM
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.param = iprot.readString();
              struct.setParamIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // ATTR_NAMES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list62 = iprot.readListBegin();
                struct.attr_names = new java.util.ArrayList<java.lang.String>(_list62.size);
                java.lang.String _elem63;
                for (int _i64 = 0; _i64 < _list62.size; ++_i64)
                {
                  _elem63 = iprot.readString();
                  struct.attr_names.add(_elem63);
                }
                iprot.readListEnd();
              }
              struct.setAttr_namesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ATTR_VALUES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list65 = iprot.readListBegin();
                struct.attr_values = new java.util.ArrayList<java.util.List<java.lang.String>>(_list65.size);
                java.util.List<java.lang.String> _elem66;
                for (int _i67 = 0; _i67 < _list65.size; ++_i67)
                {
                  {
                    org.apache.thrift.protocol.TList _list68 = iprot.readListBegin();
                    _elem66 = new java.util.ArrayList<java.lang.String>(_list68.size);
                    java.lang.String _elem69;
                    for (int _i70 = 0; _i70 < _list68.size; ++_i70)
                    {
                      _elem69 = iprot.readString();
                      _elem66.add(_elem69);
                    }
                    iprot.readListEnd();
                  }
                  struct.attr_values.add(_elem66);
                }
                iprot.readListEnd();
              }
              struct.setAttr_valuesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // SCORES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list71 = iprot.readListBegin();
                struct.scores = new java.util.ArrayList<java.lang.Double>(_list71.size);
                double _elem72;
                for (int _i73 = 0; _i73 < _list71.size; ++_i73)
                {
                  _elem72 = iprot.readDouble();
                  struct.scores.add(_elem72);
                }
                iprot.readListEnd();
              }
              struct.setScoresIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // TAKEN_BY
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list74 = iprot.readListBegin();
                struct.taken_by = new java.util.ArrayList<java.lang.String>(_list74.size);
                java.lang.String _elem75;
                for (int _i76 = 0; _i76 < _list74.size; ++_i76)
                {
                  _elem75 = iprot.readString();
                  struct.taken_by.add(_elem75);
                }
                iprot.readListEnd();
              }
              struct.setTaken_byIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // JUSTIFICATIONS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list77 = iprot.readListBegin();
                struct.justifications = new java.util.ArrayList<java.util.List<java.lang.String>>(_list77.size);
                java.util.List<java.lang.String> _elem78;
                for (int _i79 = 0; _i79 < _list77.size; ++_i79)
                {
                  {
                    org.apache.thrift.protocol.TList _list80 = iprot.readListBegin();
                    _elem78 = new java.util.ArrayList<java.lang.String>(_list80.size);
                    java.lang.String _elem81;
                    for (int _i82 = 0; _i82 < _list80.size; ++_i82)
                    {
                      _elem81 = iprot.readString();
                      _elem78.add(_elem81);
                    }
                    iprot.readListEnd();
                  }
                  struct.justifications.add(_elem78);
                }
                iprot.readListEnd();
              }
              struct.setJustificationsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SubobjectiveDetails struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.param != null) {
        oprot.writeFieldBegin(PARAM_FIELD_DESC);
        oprot.writeString(struct.param);
        oprot.writeFieldEnd();
      }
      if (struct.attr_names != null) {
        oprot.writeFieldBegin(ATTR_NAMES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.attr_names.size()));
          for (java.lang.String _iter83 : struct.attr_names)
          {
            oprot.writeString(_iter83);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.attr_values != null) {
        oprot.writeFieldBegin(ATTR_VALUES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, struct.attr_values.size()));
          for (java.util.List<java.lang.String> _iter84 : struct.attr_values)
          {
            {
              oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, _iter84.size()));
              for (java.lang.String _iter85 : _iter84)
              {
                oprot.writeString(_iter85);
              }
              oprot.writeListEnd();
            }
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.scores != null) {
        oprot.writeFieldBegin(SCORES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.DOUBLE, struct.scores.size()));
          for (double _iter86 : struct.scores)
          {
            oprot.writeDouble(_iter86);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.taken_by != null) {
        oprot.writeFieldBegin(TAKEN_BY_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.taken_by.size()));
          for (java.lang.String _iter87 : struct.taken_by)
          {
            oprot.writeString(_iter87);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.justifications != null) {
        oprot.writeFieldBegin(JUSTIFICATIONS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, struct.justifications.size()));
          for (java.util.List<java.lang.String> _iter88 : struct.justifications)
          {
            {
              oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, _iter88.size()));
              for (java.lang.String _iter89 : _iter88)
              {
                oprot.writeString(_iter89);
              }
              oprot.writeListEnd();
            }
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SubobjectiveDetailsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SubobjectiveDetailsTupleScheme getScheme() {
      return new SubobjectiveDetailsTupleScheme();
    }
  }

  private static class SubobjectiveDetailsTupleScheme extends org.apache.thrift.scheme.TupleScheme<SubobjectiveDetails> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SubobjectiveDetails struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetParam()) {
        optionals.set(0);
      }
      if (struct.isSetAttr_names()) {
        optionals.set(1);
      }
      if (struct.isSetAttr_values()) {
        optionals.set(2);
      }
      if (struct.isSetScores()) {
        optionals.set(3);
      }
      if (struct.isSetTaken_by()) {
        optionals.set(4);
      }
      if (struct.isSetJustifications()) {
        optionals.set(5);
      }
      oprot.writeBitSet(optionals, 6);
      if (struct.isSetParam()) {
        oprot.writeString(struct.param);
      }
      if (struct.isSetAttr_names()) {
        {
          oprot.writeI32(struct.attr_names.size());
          for (java.lang.String _iter90 : struct.attr_names)
          {
            oprot.writeString(_iter90);
          }
        }
      }
      if (struct.isSetAttr_values()) {
        {
          oprot.writeI32(struct.attr_values.size());
          for (java.util.List<java.lang.String> _iter91 : struct.attr_values)
          {
            {
              oprot.writeI32(_iter91.size());
              for (java.lang.String _iter92 : _iter91)
              {
                oprot.writeString(_iter92);
              }
            }
          }
        }
      }
      if (struct.isSetScores()) {
        {
          oprot.writeI32(struct.scores.size());
          for (double _iter93 : struct.scores)
          {
            oprot.writeDouble(_iter93);
          }
        }
      }
      if (struct.isSetTaken_by()) {
        {
          oprot.writeI32(struct.taken_by.size());
          for (java.lang.String _iter94 : struct.taken_by)
          {
            oprot.writeString(_iter94);
          }
        }
      }
      if (struct.isSetJustifications()) {
        {
          oprot.writeI32(struct.justifications.size());
          for (java.util.List<java.lang.String> _iter95 : struct.justifications)
          {
            {
              oprot.writeI32(_iter95.size());
              for (java.lang.String _iter96 : _iter95)
              {
                oprot.writeString(_iter96);
              }
            }
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SubobjectiveDetails struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(6);
      if (incoming.get(0)) {
        struct.param = iprot.readString();
        struct.setParamIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list97 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.attr_names = new java.util.ArrayList<java.lang.String>(_list97.size);
          java.lang.String _elem98;
          for (int _i99 = 0; _i99 < _list97.size; ++_i99)
          {
            _elem98 = iprot.readString();
            struct.attr_names.add(_elem98);
          }
        }
        struct.setAttr_namesIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list100 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, iprot.readI32());
          struct.attr_values = new java.util.ArrayList<java.util.List<java.lang.String>>(_list100.size);
          java.util.List<java.lang.String> _elem101;
          for (int _i102 = 0; _i102 < _list100.size; ++_i102)
          {
            {
              org.apache.thrift.protocol.TList _list103 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
              _elem101 = new java.util.ArrayList<java.lang.String>(_list103.size);
              java.lang.String _elem104;
              for (int _i105 = 0; _i105 < _list103.size; ++_i105)
              {
                _elem104 = iprot.readString();
                _elem101.add(_elem104);
              }
            }
            struct.attr_values.add(_elem101);
          }
        }
        struct.setAttr_valuesIsSet(true);
      }
      if (incoming.get(3)) {
        {
          org.apache.thrift.protocol.TList _list106 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.DOUBLE, iprot.readI32());
          struct.scores = new java.util.ArrayList<java.lang.Double>(_list106.size);
          double _elem107;
          for (int _i108 = 0; _i108 < _list106.size; ++_i108)
          {
            _elem107 = iprot.readDouble();
            struct.scores.add(_elem107);
          }
        }
        struct.setScoresIsSet(true);
      }
      if (incoming.get(4)) {
        {
          org.apache.thrift.protocol.TList _list109 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.taken_by = new java.util.ArrayList<java.lang.String>(_list109.size);
          java.lang.String _elem110;
          for (int _i111 = 0; _i111 < _list109.size; ++_i111)
          {
            _elem110 = iprot.readString();
            struct.taken_by.add(_elem110);
          }
        }
        struct.setTaken_byIsSet(true);
      }
      if (incoming.get(5)) {
        {
          org.apache.thrift.protocol.TList _list112 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, iprot.readI32());
          struct.justifications = new java.util.ArrayList<java.util.List<java.lang.String>>(_list112.size);
          java.util.List<java.lang.String> _elem113;
          for (int _i114 = 0; _i114 < _list112.size; ++_i114)
          {
            {
              org.apache.thrift.protocol.TList _list115 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
              _elem113 = new java.util.ArrayList<java.lang.String>(_list115.size);
              java.lang.String _elem116;
              for (int _i117 = 0; _i117 < _list115.size; ++_i117)
              {
                _elem116 = iprot.readString();
                _elem113.add(_elem116);
              }
            }
            struct.justifications.add(_elem113);
          }
        }
        struct.setJustificationsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

